= Isconna
Rui LIU (@liurui39660)
:toc: macro
:toc-title:

C++ implementation of

* https://arxiv.org/pdf/2104.01632[Isconna: Streaming Anomaly Detection with Frequency and Patterns]. _Rui Liu, Siddharth Bhatia, Bryan Hooi_. (Under Review)

image::asset/Overview.Flowchart.svg[]

[discrete]
=== Table of Contents

toc::[]

== Demo

If you find `dep/AUROC` and `dep/mio` are empty, use this command to clone the dependencies.

`git submodule update --init`

The following steps are necessary before choosing the standalone or the docker build.

. Open a terminal (Linux/macOS) or a Visual Studio Developer Command Prompt (Windows)
. `cd` to the project root `Isconna`
. `mkdir out`
. `tar -xf data/data.zip -C data`
** This also works for Windows 10

=== Standalone

If you want to build and run directly on your machine ...

. `cmake -DCMAKE_BUILD_TYPE=Release -GNinja -S . -B build/release`
** You can remove `-GNinja` if you don't have https://github.com/ninja-build/ninja/releases/latest[`ninja`]
. `cmake --build build/release --target Demo`
. `build\release\Demo.exe` (Windows) or `build/release/Demo` (Linux/macOS)

The demo runs Isconna-EO on CIC-IDS2018 (`data/CIC-IDS2018/processed/Data.csv`) and prints ROC-AUC.
An empty `out/Score.tsv` will be created.

=== Docker

If you want to use docker, at the cost of some speed ...

. `docker build -t isconna .`
. `docker run -v %cd%\data:/Isconna/data -v %cd%\out:/Isconna/out isconna`

This does the same thing as the standalone method.

The image also includes dependencies for experiments.

== Requirement

.Core
* C++11

.Demo
* https://github.com/mandreyel/mio[mio] (memory mapping, i.e., I/O)
* https://github.com/liurui39660/AUROC[AUROC] (metric)

.Experiment
* https://github.com/mandreyel/mio[mio] (memory mapping, i.e., I/O)
* https://github.com/liurui39660/AUROC[AUROC] (metric)
* TBB (`libtbb-dev`, parallelization)
* SQLite (`libsqlite3-dev`, result storage)

== Customization

Only for the demo (`example/Demo.cpp`).

=== Export Raw Scores

Change `shouldExportRawScore` to `true`.

`out/Score.tsv` has 4 columns: the final anomaly score, the unweighted frequency, width and gap scores.

`out/Score.tsv` is a tab-separated values file.

=== Switch Cores

Cores are declared within the body. You can search for the variable `isc`, then uncomment the chosen core, and comment out the others.

=== Different Parameters / Datasets

Parameters and dataset paths are specified in the Parameter section of the code.

=== External Dataset + `Demo.cpp`

You need to prepare three files:

* Meta file
** Only includes an integer `n`, the number of records in the dataset
** Assign its path to `pathMeta`
** E.g., `data/CIC-IDS2018/processed/Meta.txt`
* Data file
** A header-less csv file with shape `[n,3]`
** Each row includes 3 integers: source, destination and timestamp
** Timestamps should start from 1 and be continuous
** Assign its path to `pathData`
** E.g., `data/CIC-IDS2018/processed/Data.csv`
* Label file
** A header-less text file with shape `[n,1]`
** Each row includes 1 integer: 0 if normal, 1 if anomalous
** Assign its path to `pathLabel`
** E.g., `data/CIC-IDS2018/processed/Label.csv`

=== External Dataset + Custom Runner

. Include headers `src/EdgeNodeCore.hpp` and/or `src/EdgeOnlyCore.hpp`
. Instantiate cores with required parameters
** Number of CMS rows
** Number of CMS columns
** Decay factor (default is 0, i.e., keep nothing)
. Call `operator()` on individual records
** Unweighted intermediate scores are returned via the last 3 arguments

== Citation

Please consider citing our arXiv preprint if you want to use our code for you research.

----
@misc{liu2021isconna,
      title={Isconna: Streaming Anomaly Detection with Frequency and Patterns},
      author={Rui Liu and Siddharth Bhatia and Bryan Hooi},
      year={2021},
      eprint={2104.01632},
      archivePrefix={arXiv},
      primaryClass={cs.LG}
}
----

== Feedback

If you have any suggestion about this document, source code, etc., please feel free to open an issue.
