name: Test.Demo
on:
  workflow_dispatch:
  push:
    paths:
      - 'CMakeLists.txt'
      - 'dep/**'
      - 'src/**'
      - 'include/**'
      - 'example/**'
      - '.github/workflows/Test.Demo.yml'
jobs:
  Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: ilammy/msvc-dev-cmd@v1
      - run: mkdir out
      - name: Extract datasets
        run: 7z x data/data.zip -odata
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl -G"NMake Makefiles" -S . -B build/release
      - name: Build
        run: cmake --build build/release --target Demo
      - name: Run
        run: build\release\Demo.exe
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: mkdir out
      - name: Extract datasets
        run: 7z x data/data.zip -odata
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -S . -B build/release
      - name: Build
        run: cmake --build build/release --target Demo
      - name: Run
        run: build/release/Demo
  Docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: mkdir out
      - name: Extract datasets
        run: 7z x data/data.zip -odata
      - name: Build
        run: docker build -t isconna .
      - name: Run
        run: docker run -v $PWD/data:/Isconna/data -v $PWD/out:/Isconna/out isconna
